apiVersion: v1
kind: Secret
metadata:
  name: {{ include "energyhistorian.fullname" . }}-secrets
  labels:
    {{- include "energyhistorian.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  postgres-url: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.postgres.username .Values.postgres.password (include "energyhistorian.postgresHost" .) .Values.postgres.database | quote }}
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
  s3-access-key-id: {{ .Values.minio.rootUser | quote }}
  s3-secret-access-key: {{ .Values.minio.rootPassword | quote }}
  clickhouse-user: {{ .Values.clickhouse.username | quote }}
  clickhouse-password: {{ .Values.clickhouse.password | quote }}
