WITH

region_dispatch AS (
    SELECT
        SETTLEMENTDATE,
        REGIONID,
        avg(RRP) AS RRP,
        avg(TOTALDEMAND) AS TOTALDEMAND,
        avg(DEMANDFORECAST) AS DEMANDFORECAST,
        avg(DISPATCHABLEGENERATION) AS DISPATCHABLEGENERATION,
        avg(NETINTERCHANGE) AS NETINTERCHANGE,
        avg(AVAILABLEGENERATION) AS AVAILABLEGENERATION,
        avg(EXCESSGENERATION) AS EXCESSGENERATION,
        avg(RAISE6SECDISPATCH) AS RAISE6SECDISPATCH,
        avg(RAISE60SECDISPATCH) AS RAISE60SECDISPATCH,
        avg(RAISE5MINDISPATCH) AS RAISE5MINDISPATCH,
        avg(RAISEREGLOCALDISPATCH) AS RAISEREGLOCALDISPATCH,
        avg(LOWER6SECDISPATCH) AS LOWER6SECDISPATCH,
        avg(LOWER60SECDISPATCH) AS LOWER60SECDISPATCH,
        avg(LOWER5MINDISPATCH) AS LOWER5MINDISPATCH,
        avg(LOWERREGLOCALDISPATCH) AS LOWERREGLOCALDISPATCH
    FROM semantic.daily_region_dispatch
    GROUP BY SETTLEMENTDATE, REGIONID
)

SELECT
    REGIONID,
    market,
    round(sum(enabled_mw / 12.0), 2) AS enabled_mwh_proxy
FROM (
    SELECT SETTLEMENTDATE, REGIONID, 'RAISE' AS market, RAISE6SECDISPATCH + RAISE60SECDISPATCH + RAISE5MINDISPATCH + RAISEREGLOCALDISPATCH AS enabled_mw FROM region_dispatch
    UNION ALL
    SELECT SETTLEMENTDATE, REGIONID, 'LOWER' AS market, LOWER6SECDISPATCH + LOWER60SECDISPATCH + LOWER5MINDISPATCH + LOWERREGLOCALDISPATCH AS enabled_mw FROM region_dispatch
) f
WHERE SETTLEMENTDATE >= now() - INTERVAL 7 DAY
GROUP BY REGIONID, market
ORDER BY REGIONID, market