WITH

interconnector_dispatch AS (
    SELECT
        SETTLEMENTDATE,
        INTERCONNECTORID,
        avg(MWFLOW) AS MWFLOW,
        avg(METEREDMWFLOW) AS METEREDMWFLOW,
        avg(MWLOSSES) AS MWLOSSES,
        avg(EXPORTLIMIT) AS EXPORTLIMIT,
        avg(IMPORTLIMIT) AS IMPORTLIMIT,
        avg(MARGINALVALUE) AS MARGINALVALUE
    FROM semantic.dispatch_interconnectorres
    GROUP BY SETTLEMENTDATE, INTERCONNECTORID
)

SELECT
    SETTLEMENTDATE,
    INTERCONNECTORID,
    round(MWFLOW, 2) AS flow_mw,
    round(EXPORTLIMIT, 2) AS export_limit_mw,
    round(IMPORTLIMIT, 2) AS import_limit_mw
FROM interconnector_dispatch
WHERE SETTLEMENTDATE >= now() - INTERVAL 7 DAY
  AND (
      abs(MWFLOW - EXPORTLIMIT) <= 1
      OR abs(MWFLOW + IMPORTLIMIT) <= 1
      OR abs(abs(MWFLOW) - greatest(EXPORTLIMIT, IMPORTLIMIT)) <= 1
  )
ORDER BY SETTLEMENTDATE DESC, INTERCONNECTORID