WITH

price_dispatch AS (
    SELECT
        SETTLEMENTDATE,
        REGIONID,
        avg(RRP) AS RRP,
        avg(RAISE6SECRRP) AS RAISE6SECRRP,
        avg(RAISE60SECRRP) AS RAISE60SECRRP,
        avg(RAISE5MINRRP) AS RAISE5MINRRP,
        avg(RAISEREGRRP) AS RAISEREGRRP,
        avg(RAISE1SECRRP) AS RAISE1SECRRP,
        avg(LOWER6SECRRP) AS LOWER6SECRRP,
        avg(LOWER60SECRRP) AS LOWER60SECRRP,
        avg(LOWER5MINRRP) AS LOWER5MINRRP,
        avg(LOWERREGRRP) AS LOWERREGRRP,
        avg(LOWER1SECRRP) AS LOWER1SECRRP
    FROM semantic.dispatch_price
    GROUP BY SETTLEMENTDATE, REGIONID
)

SELECT
    toDate(SETTLEMENTDATE) AS trading_day,
    REGIONID,
    round(avg((RAISE6SECRRP + RAISE60SECRRP + RAISE5MINRRP + RAISEREGRRP + LOWER6SECRRP + LOWER60SECRRP + LOWER5MINRRP + LOWERREGRRP) / 8.0), 2) AS avg_fcas_price,
    round(avg(RRP), 2) AS avg_energy_price,
    round(avg((RAISE6SECRRP + RAISE60SECRRP + RAISE5MINRRP + RAISEREGRRP + LOWER6SECRRP + LOWER60SECRRP + LOWER5MINRRP + LOWERREGRRP) / 8.0) / nullIf(avg(RRP), 0), 3) AS fcas_to_energy_ratio
FROM price_dispatch
GROUP BY trading_day, REGIONID
ORDER BY trading_day, REGIONID