use anyhow::{Context, Result};
use scraper::{Html, Selector};
use tracing::info;

use crate::catalog::{MmsColumn, MmsPackage, MmsTable};

pub const BASE_URL: &str = "https://nemweb.com.au/Reports/Current/MMSDataModelReport/Electricity/Electricity%20Data%20Model%20Report_files";
pub const TOC_URL: &str = "https://nemweb.com.au/Reports/Current/MMSDataModelReport/Electricity/Electricity%20Data%20Model%20Report_files/Electricity%20Data%20Model%20Report_toc.htm";

/// Fetches the TOC and discovers which HTML pages belong to which package.
pub async fn fetch_toc(client: &reqwest::Client) -> Result<Vec<TocEntry>> {
    let html = client
        .get(TOC_URL)
        .send()
        .await?
        .text()
        .await
        .context("Failed to fetch MMS Data Model TOC")?;

    parse_toc(&html)
}

#[derive(Debug, Clone)]
pub struct TocEntry {
    pub package_name: String,
    pub page_files: Vec<String>,
}

/// Parse the TOC HTML generated by PowerDesigner.
/// Structure: `<a href="Elec3.htm#1">Package: CONFIGURATION</a>`
///            `<a href="Elec4.htm#1">Table: MMS_DATA_MODEL_AUDIT</a>`
pub fn parse_toc(html: &str) -> Result<Vec<TocEntry>> {
    let doc = Html::parse_document(html);
    let link_sel = Selector::parse("a.Browser").unwrap();

    let mut entries: Vec<TocEntry> = Vec::new();
    let mut current_package: Option<String> = None;

    for element in doc.select(&link_sel) {
        let text = element.text().collect::<String>().trim().to_string();
        let href = element.value().attr("href").unwrap_or_default().to_string();

        if text.is_empty() || !href.contains(".htm") {
            continue;
        }

        // Extract filename without anchor (e.g., "Elec3.htm#1" -> "Elec3.htm")
        let filename = href.split('#').next().unwrap_or(&href).to_string();

        if text.starts_with("Package: ") {
            let package_name = text.trim_start_matches("Package: ").trim().to_string();
            current_package = Some(package_name.clone());
            if !entries.iter().any(|e| e.package_name == package_name) {
                entries.push(TocEntry {
                    package_name,
                    page_files: vec![filename],
                });
            }
        } else if text.starts_with("Table: ") {
            // Table entry — add its page to the current package
            if let Some(ref pkg) = current_package {
                if let Some(entry) = entries.iter_mut().find(|e| e.package_name == *pkg) {
                    if !entry.page_files.contains(&filename) {
                        entry.page_files.push(filename);
                    }
                }
            }
        }
    }

    Ok(entries)
}

/// Fetches and parses a single MMS Data Model HTML page.
pub async fn fetch_and_parse_page(
    client: &reqwest::Client,
    filename: &str,
    package_id: &str,
) -> Result<Vec<MmsTable>> {
    let url = format!("{}/{}", BASE_URL, filename);
    let html = client
        .get(&url)
        .send()
        .await?
        .text()
        .await
        .with_context(|| format!("Failed to fetch {}", url))?;

    parse_page(&html, package_id)
}

/// Parses a single HTML page from the MMS Data Model report (PowerDesigner generated).
///
/// Structure per table on a page:
/// ```html
/// <h2><a name="1">Table: TABLE_NAME</a></h2>
/// <h3><a name="2">TABLE_NAME</a></h3>
/// <table class="Form"> ... Name, Comment rows ... </table>
/// <h3>Description</h3>
/// <table class="Text"> ... Source, Volume paragraphs ... </table>
/// <h3>Notes</h3>
/// <table class="Grid"> ... Visibility row ... </table>
/// <h3>Primary Key Columns</h3>
/// <table class="Grid"> ... PK column names ... </table>
/// <h3>Content</h3>
/// <table class="Grid"> ... Name, Data Type, Mandatory, Comment columns ... </table>
/// ```
fn parse_page(html: &str, package_id: &str) -> Result<Vec<MmsTable>> {
    let doc = Html::parse_document(html);
    let mut tables = Vec::new();

    // Use CSS selectors to find all relevant elements in document order.
    // The PowerDesigner HTML has a flat structure (all h2/h3/table are direct body children)
    // but html5ever's foster parenting may rearrange them. So we use select() which traverses
    // the full tree in document order.

    #[derive(Debug)]
    enum DocElement {
        TableHeader(String),
        SectionHeader(String),
        HtmlTableWithClass(String, Vec<Vec<Vec<String>>>),
        DescriptionBlock(Vec<(String, String)>),
    }

    let mut elements: Vec<DocElement> = Vec::new();

    let mut current_table_name: Option<String> = None;
    let mut current_comment = String::new();
    let mut current_source = String::new();
    let mut current_volume = String::new();
    let mut current_visibility = String::new();
    let mut current_notes = String::new();
    let mut current_pk_columns: Vec<String> = Vec::new();
    let mut current_index_columns: Vec<String> = Vec::new();
    let mut current_columns: Vec<MmsColumn> = Vec::new();
    let mut current_section = String::new();

    let h2_sel = Selector::parse("h2").unwrap();
    let h3_sel = Selector::parse("h3").unwrap();
    let table_sel = Selector::parse("table").unwrap();
    let tr_sel = Selector::parse("tr").unwrap();
    let td_sel = Selector::parse("td").unwrap();
    let p_sel = Selector::parse("p").unwrap();
    let span_sel = Selector::parse("span").unwrap();

    // Collect elements with their node ID for sorting into document order.
    // scraper's select() returns in document order, but we need to interleave
    // h2, h3, and table results. Use the node's tree ID as sort key.
    let mut positioned: Vec<(ego_tree::NodeId, DocElement)> = Vec::new();

    for elem in doc.select(&h2_sel) {
        let text = elem.text().collect::<String>().trim().to_string();
        if text.starts_with("Table:") {
            let name = text.strip_prefix("Table:").unwrap().trim().to_string();
            positioned.push((elem.id(), DocElement::TableHeader(name)));
        }
    }

    for elem in doc.select(&h3_sel) {
        let text = elem.text().collect::<String>().trim().to_string();
        if !text.is_empty() {
            positioned.push((elem.id(), DocElement::SectionHeader(text)));
        }
    }

    for elem in doc.select(&table_sel) {
        // Skip tables nested inside other tables
        let is_nested = elem
            .ancestors()
            .filter_map(scraper::ElementRef::wrap)
            .any(|a| a.value().name() == "table");
        if is_nested {
            continue;
        }

        let class = elem.value().attr("class").unwrap_or_default().to_string();

        if class == "Text" {
            let mut pairs: Vec<(String, String)> = Vec::new();
            let mut cur_label = String::new();
            for p in elem.select(&p_sel) {
                let p_text = p.text().collect::<String>().trim().to_string();
                let has_label_span = p.select(&span_sel).any(|s| {
                    let style = s.value().attr("style").unwrap_or_default();
                    style.contains("Arial Black") || style.contains("color:#FF0000")
                });
                if has_label_span {
                    cur_label = p_text;
                } else if !p_text.is_empty() && !cur_label.is_empty() {
                    pairs.push((cur_label.clone(), p_text));
                }
            }
            positioned.push((elem.id(), DocElement::DescriptionBlock(pairs)));
        } else if class != "NavGroup" {
            let rows: Vec<Vec<Vec<String>>> = elem
                .select(&tr_sel)
                .map(|row| {
                    row.select(&td_sel)
                        .map(|cell| {
                            let p_texts: Vec<String> = cell
                                .select(&p_sel)
                                .map(|p| p.text().collect::<String>().trim().to_string())
                                .collect();
                            if p_texts.is_empty() {
                                vec![cell.text().collect::<String>().trim().to_string()]
                            } else {
                                p_texts
                            }
                        })
                        .collect()
                })
                .collect();
            positioned.push((elem.id(), DocElement::HtmlTableWithClass(class, rows)));
        }
    }

    // Sort by node ID to get document order
    positioned.sort_by_key(|(id, _)| *id);
    for (_, elem) in positioned {
        elements.push(elem);
    }

    // Process elements in order
    for elem in &elements {
        match elem {
            DocElement::TableHeader(name) => {
                // Flush previous table
                flush_table(
                    &mut tables,
                    package_id,
                    &mut current_table_name,
                    &mut current_comment,
                    &mut current_source,
                    &mut current_volume,
                    &mut current_visibility,
                    &mut current_notes,
                    &mut current_pk_columns,
                    &mut current_index_columns,
                    &mut current_columns,
                );
                current_table_name = Some(name.clone());
                current_section.clear();
            }
            DocElement::SectionHeader(text) => {
                current_section = text.clone();
            }
            DocElement::DescriptionBlock(pairs) => {
                if current_table_name.is_none() {
                    continue;
                }
                for (label, value) in pairs {
                    match label.as_str() {
                        "Source" => current_source = value.clone(),
                        "Volume" => current_volume = value.clone(),
                        "Note" | "Notes" => {
                            if !current_notes.is_empty() {
                                current_notes.push(' ');
                            }
                            current_notes.push_str(value);
                        }
                        _ => {}
                    }
                }
            }
            DocElement::HtmlTableWithClass(class, rows) => {
                if current_table_name.is_none() {
                    continue;
                }

                if class == "Form" {
                    // Form table: Name/Comment metadata
                    for row in rows {
                        if row.len() >= 2 {
                            let label = row[0].join(" ").to_lowercase();
                            let value = row[1].join(" ");
                            if label.contains("comment") {
                                current_comment = value;
                            }
                        }
                    }
                } else if current_section.contains("Primary Key") {
                    for row in rows.iter().skip(1) {
                        if let Some(cells) = row.first() {
                            let name = cells.join("").trim().to_string();
                            if !name.is_empty() && name != "Name" {
                                current_pk_columns.push(name);
                            }
                        }
                    }
                } else if current_section == "Content" || current_section.starts_with("Content") {
                    // Column definitions: Name | Data Type | Mandatory | Comment
                    parse_content_rows(rows, &mut current_columns);
                } else if current_section.contains("Index") {
                    for row in rows.iter().skip(1) {
                        if let Some(cells) = row.first() {
                            let name = cells.join("").trim().to_string();
                            if !name.is_empty() && name != "Name" {
                                current_index_columns.push(name);
                            }
                        }
                    }
                } else if current_section.contains("Notes") {
                    for row in rows.iter().skip(1) {
                        if row.len() >= 3 {
                            let label = row[0].join("").to_lowercase();
                            let value = row[2].join("");
                            if label.contains("visibility") {
                                current_visibility = value.trim().to_string();
                            }
                        }
                    }
                }
            }
        }
    }

    // Flush last table
    flush_table(
        &mut tables,
        package_id,
        &mut current_table_name,
        &mut current_comment,
        &mut current_source,
        &mut current_volume,
        &mut current_visibility,
        &mut current_notes,
        &mut current_pk_columns,
        &mut current_index_columns,
        &mut current_columns,
    );

    Ok(tables)
}

fn flush_table(
    tables: &mut Vec<MmsTable>,
    package_id: &str,
    current_table_name: &mut Option<String>,
    current_comment: &mut String,
    current_source: &mut String,
    current_volume: &mut String,
    current_visibility: &mut String,
    current_notes: &mut String,
    current_pk_columns: &mut Vec<String>,
    current_index_columns: &mut Vec<String>,
    current_columns: &mut Vec<MmsColumn>,
) {
    if let Some(table_name) = current_table_name.take() {
        for col in current_columns.iter_mut() {
            if current_pk_columns.contains(&col.column_name) {
                col.is_primary_key = true;
            }
        }
        if !current_columns.is_empty() {
            tables.push(MmsTable {
                package_id: package_id.to_string(),
                table_name,
                description: std::mem::take(current_comment),
                source_notes: std::mem::take(current_source),
                volume_notes: std::mem::take(current_volume),
                visibility: std::mem::take(current_visibility),
                additional_notes: std::mem::take(current_notes),
                primary_key_columns: std::mem::take(current_pk_columns),
                index_columns: std::mem::take(current_index_columns),
                columns: std::mem::take(current_columns),
            });
        } else {
            // Clear state even if no columns found
            current_comment.clear();
            current_source.clear();
            current_volume.clear();
            current_visibility.clear();
            current_notes.clear();
            current_pk_columns.clear();
            current_index_columns.clear();
        }
    }
}

fn parse_content_rows(rows: &[Vec<Vec<String>>], columns: &mut Vec<MmsColumn>) {
    // Skip header row, parse: Name | Data Type | Mandatory | Comment
    for row in rows.iter().skip(1) {
        if row.len() < 4 {
            continue;
        }
        let col_name = row[0].join("").trim().to_string();
        let oracle_type = row[1].join("").trim().to_string();
        let mandatory_str = row[2].join("").trim().to_string();
        let description = row[3].join(" ").trim().to_string();

        if col_name.is_empty() || col_name == "Name" {
            continue;
        }

        let is_mandatory = mandatory_str.contains('X') || mandatory_str == "1";
        let units = extract_units(&description);
        let valid_values = extract_valid_values(&description);

        columns.push(MmsColumn {
            column_name: col_name,
            ordinal: columns.len(),
            oracle_type,
            is_mandatory,
            is_primary_key: false,
            description,
            units,
            valid_values,
        });
    }
}

/// Extract units from a column description (e.g., "MW", "$/MWh", "%").
fn extract_units(description: &str) -> Option<String> {
    // Common unit patterns in AEMO column descriptions
    let unit_patterns = [
        ("$/MWh", "$/MWh"),
        ("$/MW/hr", "$/MW/hr"),
        ("$/MW", "$/MW"),
        ("MWh", "MWh"),
        (" MW", "MW"),
        ("-MW", "MW"),
        ("(MW)", "MW"),
        ("MVAr", "MVAr"),
        ("Hz", "Hz"),
        (" %", "%"),
        ("(%)", "%"),
        ("minutes", "minutes"),
        ("MW per minute", "MW/min"),
        ("MW/Min", "MW/min"),
    ];

    for (pattern, unit) in &unit_patterns {
        if description.contains(pattern) {
            return Some(unit.to_string());
        }
    }

    None
}

/// Extract valid values/enum descriptions from column descriptions.
fn extract_valid_values(description: &str) -> Option<String> {
    // Look for patterns like "0=normal / 1=Supply Scarcity" or "GENERATOR, LOAD, BIDIRECTIONAL"
    if description.contains('=') && (description.contains('/') || description.contains(',')) {
        // Extract the enum-like part
        // Common patterns: "Key: 0=X / 1=Y" or "0 = X, 1 = Y"
        if let Some(start) = description.find(|c: char| c.is_ascii_digit()) {
            let rest = &description[start..];
            if rest.contains('=') {
                return Some(rest.trim_end_matches('.').trim().to_string());
            }
        }
    }

    // Look for quoted value lists
    if description.contains('\'') {
        let parts: Vec<&str> = description.split('\'').collect();
        let values: Vec<String> = parts
            .chunks(2)
            .filter_map(|chunk| {
                if chunk.len() == 2 {
                    let val = chunk[1].trim();
                    if !val.is_empty() && val.len() < 30 {
                        Some(val.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                }
            })
            .collect();
        if values.len() >= 2 {
            return Some(values.join(", "));
        }
    }

    None
}

/// Fetch and parse the entire MMS Data Model.
pub async fn fetch_full_model(
    client: &reqwest::Client,
) -> Result<(Vec<MmsPackage>, Vec<MmsTable>)> {
    info!("Fetching MMS Data Model table of contents...");
    let toc = fetch_toc(client).await?;
    info!("Found {} packages in TOC", toc.len());

    let mut all_tables = Vec::new();
    let mut packages = Vec::new();

    for entry in &toc {
        let mut package_tables = Vec::new();

        for filename in &entry.page_files {
            info!(
                "Fetching page {} for package {}",
                filename, entry.package_name
            );
            match fetch_and_parse_page(client, filename, &entry.package_name).await {
                Ok(page_tables) => {
                    info!("  Found {} tables on {}", page_tables.len(), filename);
                    package_tables.extend(page_tables);
                }
                Err(e) => {
                    tracing::warn!("  Failed to parse {}: {}", filename, e);
                }
            }
        }

        packages.push(MmsPackage {
            package_id: entry.package_name.clone(),
            table_count: package_tables.len(),
        });
        all_tables.extend(package_tables);
    }

    info!(
        "Parsed {} packages, {} tables total",
        packages.len(),
        all_tables.len()
    );

    Ok((packages, all_tables))
}

/// Alternative: parse from pre-downloaded HTML files on disk.
pub fn parse_model_from_files(
    dir: &std::path::Path,
    toc_entries: &[TocEntry],
) -> Result<(Vec<MmsPackage>, Vec<MmsTable>)> {
    let mut all_tables = Vec::new();
    let mut packages = Vec::new();

    for entry in toc_entries {
        let mut package_tables = Vec::new();

        for filename in &entry.page_files {
            let path = dir.join(filename);
            if !path.exists() {
                continue;
            }
            let html = std::fs::read_to_string(&path)
                .with_context(|| format!("Failed to read {}", path.display()))?;

            match parse_page(&html, &entry.package_name) {
                Ok(page_tables) => package_tables.extend(page_tables),
                Err(e) => {
                    tracing::warn!("Failed to parse {}: {}", path.display(), e);
                }
            }
        }

        packages.push(MmsPackage {
            package_id: entry.package_name.clone(),
            table_count: package_tables.len(),
        });
        all_tables.extend(package_tables);
    }

    Ok((packages, all_tables))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_units() {
        assert_eq!(
            extract_units("Target MW Flow for next 5 mins"),
            Some("MW".to_string())
        );
        assert_eq!(
            extract_units("Regional Reference Price ($/MWh spot price)"),
            Some("$/MWh".to_string())
        );
        assert_eq!(extract_units("Ramp down rate in dispatch"), None);
        assert_eq!(extract_units("percentage (%)"), Some("%".to_string()));
    }

    #[test]
    fn test_extract_valid_values() {
        assert!(extract_valid_values("0=normal / 1=Supply Scarcity").is_some());
    }
}
