use crate::catalog::{FcasMarket, InterconnectorRef};

/// Seed FCAS market reference data.
/// The 10 FCAS markets in the NEM with their column locations across tables.
pub fn seed_fcas_markets() -> Vec<FcasMarket> {
    vec![
        FcasMarket {
            market_id: "RAISE6SEC".into(),
            display_name: "Raise 6 Second".into(),
            direction: "RAISE".into(),
            response_time: "6SEC".into(),
            price_column: "RAISE6SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "RAISE6SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "RAISE6SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "LOWER6SEC".into(),
            display_name: "Lower 6 Second".into(),
            direction: "LOWER".into(),
            response_time: "6SEC".into(),
            price_column: "LOWER6SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "LOWER6SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "LOWER6SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "RAISE60SEC".into(),
            display_name: "Raise 60 Second".into(),
            direction: "RAISE".into(),
            response_time: "60SEC".into(),
            price_column: "RAISE60SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "RAISE60SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "RAISE60SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "LOWER60SEC".into(),
            display_name: "Lower 60 Second".into(),
            direction: "LOWER".into(),
            response_time: "60SEC".into(),
            price_column: "LOWER60SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "LOWER60SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "LOWER60SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "RAISE5MIN".into(),
            display_name: "Raise 5 Minute".into(),
            direction: "RAISE".into(),
            response_time: "5MIN".into(),
            price_column: "RAISE5MINRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "RAISE5MINLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "RAISE5MINACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "LOWER5MIN".into(),
            display_name: "Lower 5 Minute".into(),
            direction: "LOWER".into(),
            response_time: "5MIN".into(),
            price_column: "LOWER5MINRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "LOWER5MINLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "LOWER5MINACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "RAISEREG".into(),
            display_name: "Raise Regulation".into(),
            direction: "RAISE".into(),
            response_time: "REG".into(),
            price_column: "RAISEREGRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "RAISEREGLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "RAISEREGACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "LOWERREG".into(),
            display_name: "Lower Regulation".into(),
            direction: "LOWER".into(),
            response_time: "REG".into(),
            price_column: "LOWERREGRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "LOWERREGLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "LOWERREGACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "RAISE1SEC".into(),
            display_name: "Raise 1 Second".into(),
            direction: "RAISE".into(),
            response_time: "1SEC".into(),
            price_column: "RAISE1SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "RAISE1SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "RAISE1SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
        FcasMarket {
            market_id: "LOWER1SEC".into(),
            display_name: "Lower 1 Second".into(),
            direction: "LOWER".into(),
            response_time: "1SEC".into(),
            price_column: "LOWER1SECRRP".into(),
            price_table: "DISPATCHPRICE".into(),
            volume_column: "LOWER1SECLOCALDISPATCH".into(),
            volume_table: "DISPATCHREGIONSUM".into(),
            enablement_column: "LOWER1SECACTUALAVAILABILITY".into(),
            enablement_table: "DISPATCHLOAD".into(),
        },
    ]
}

/// Seed interconnector reference data.
/// The major NEM interconnectors with common names and region mappings.
pub fn seed_interconnectors() -> Vec<InterconnectorRef> {
    vec![
        InterconnectorRef {
            interconnector_id: "NSW1-QLD1".into(),
            common_name: "QNI (Queensland-NSW Interconnector)".into(),
            from_region: "NSW1".into(),
            to_region: "QLD1".into(),
            is_mnsp: false,
        },
        InterconnectorRef {
            interconnector_id: "VIC1-NSW1".into(),
            common_name: "VNI (Victoria-NSW Interconnector)".into(),
            from_region: "VIC1".into(),
            to_region: "NSW1".into(),
            is_mnsp: false,
        },
        InterconnectorRef {
            interconnector_id: "V-SA".into(),
            common_name: "Heywood (Victoria-South Australia)".into(),
            from_region: "VIC1".into(),
            to_region: "SA1".into(),
            is_mnsp: false,
        },
        InterconnectorRef {
            interconnector_id: "V-S-MNSP1".into(),
            common_name: "Murraylink (Victoria-SA Merchant)".into(),
            from_region: "VIC1".into(),
            to_region: "SA1".into(),
            is_mnsp: true,
        },
        InterconnectorRef {
            interconnector_id: "N-Q-MNSP1".into(),
            common_name: "DirectLink (NSW-QLD Merchant)".into(),
            from_region: "NSW1".into(),
            to_region: "QLD1".into(),
            is_mnsp: true,
        },
        InterconnectorRef {
            interconnector_id: "T-V-MNSP1".into(),
            common_name: "Basslink (Tasmania-Victoria)".into(),
            from_region: "TAS1".into(),
            to_region: "VIC1".into(),
            is_mnsp: true,
        },
    ]
}
