SELECT
  coalesce(EFFECTIVE_PARTICIPANTID, PARTICIPANTID) AS PARTICIPANT,
  sum(REGISTEREDCAPACITY_MW) AS TOTAL_REGISTERED_CAPACITY_MW
FROM semantic.unit_dimension
WHERE REGISTEREDCAPACITY_MW > 0
GROUP BY coalesce(EFFECTIVE_PARTICIPANTID, PARTICIPANTID)
ORDER BY TOTAL_REGISTERED_CAPACITY_MW DESC
LIMIT 20;