WITH

bid_day AS (
    SELECT
        SETTLEMENTDATE,
        DUID,
        PARTICIPANTID,
        BIDTYPE,
        avg(VERSIONNO) AS VERSIONNO,
        avg(PRICEBAND1) AS PRICEBAND1,
        avg(PRICEBAND2) AS PRICEBAND2,
        avg(PRICEBAND3) AS PRICEBAND3,
        avg(PRICEBAND4) AS PRICEBAND4,
        avg(PRICEBAND5) AS PRICEBAND5,
        avg(PRICEBAND6) AS PRICEBAND6,
        avg(PRICEBAND7) AS PRICEBAND7,
        avg(PRICEBAND8) AS PRICEBAND8,
        avg(PRICEBAND9) AS PRICEBAND9,
        avg(PRICEBAND10) AS PRICEBAND10,
        anyLast(REBIDEXPLANATION) AS REBIDEXPLANATION
    FROM semantic.bid_dayoffer
    GROUP BY SETTLEMENTDATE, DUID, PARTICIPANTID, BIDTYPE
)
,

bid_period AS (
    SELECT
        INTERVAL_DATETIME,
        SETTLEMENTDATE,
        DUID,
        BIDTYPE,
        avg(MAXAVAIL) AS MAXAVAIL,
        avg(BANDAVAIL1) AS BANDAVAIL1,
        avg(BANDAVAIL2) AS BANDAVAIL2,
        avg(BANDAVAIL3) AS BANDAVAIL3,
        avg(BANDAVAIL4) AS BANDAVAIL4,
        avg(BANDAVAIL5) AS BANDAVAIL5,
        avg(BANDAVAIL6) AS BANDAVAIL6,
        avg(BANDAVAIL7) AS BANDAVAIL7,
        avg(BANDAVAIL8) AS BANDAVAIL8,
        avg(BANDAVAIL9) AS BANDAVAIL9,
        avg(BANDAVAIL10) AS BANDAVAIL10
    FROM semantic.bid_peroffer
    GROUP BY INTERVAL_DATETIME, SETTLEMENTDATE, DUID, BIDTYPE
)
,

unit_dim AS (
    SELECT
        DUID,
        REGIONID,
        EFFECTIVE_PARTICIPANTID,
        PARTICIPANTID,
        STATIONID,
        STATIONNAME,
        FUEL_TYPE,
        ENERGY_SOURCE,
        REGISTEREDCAPACITY_MW,
        MAXCAPACITY_MW,
        MAXSTORAGECAPACITY_MWH,
        CO2E_EMISSIONS_FACTOR,
        IS_STORAGE,
        IS_BIDIRECTIONAL,
        DISPATCHTYPE,
        SCHEDULE_TYPE
    FROM semantic.unit_dimension
)

SELECT
    u.FUEL_TYPE,
    round(avg(
        (b.PRICEBAND1 * p.BANDAVAIL1 + b.PRICEBAND2 * p.BANDAVAIL2 + b.PRICEBAND3 * p.BANDAVAIL3 +
         b.PRICEBAND4 * p.BANDAVAIL4 + b.PRICEBAND5 * p.BANDAVAIL5 + b.PRICEBAND6 * p.BANDAVAIL6 +
         b.PRICEBAND7 * p.BANDAVAIL7 + b.PRICEBAND8 * p.BANDAVAIL8 + b.PRICEBAND9 * p.BANDAVAIL9 +
         b.PRICEBAND10 * p.BANDAVAIL10) /
        nullIf(
            p.BANDAVAIL1 + p.BANDAVAIL2 + p.BANDAVAIL3 + p.BANDAVAIL4 + p.BANDAVAIL5 +
            p.BANDAVAIL6 + p.BANDAVAIL7 + p.BANDAVAIL8 + p.BANDAVAIL9 + p.BANDAVAIL10, 0
        )
    ), 2) AS avg_bid_weighted_price
FROM bid_day b
INNER JOIN bid_period p ON p.DUID = b.DUID AND p.SETTLEMENTDATE = b.SETTLEMENTDATE AND p.BIDTYPE = b.BIDTYPE
LEFT JOIN unit_dim u ON u.DUID = b.DUID
WHERE b.BIDTYPE = 'ENERGY'
GROUP BY u.FUEL_TYPE
ORDER BY avg_bid_weighted_price DESC