use crate::catalog::DataConcept;

/// Seed concept-to-table mappings derived from nemexplorer's routing rules.
/// These tell an AI agent which table/column answers a natural language question.
pub fn seed_concepts() -> Vec<DataConcept> {
    vec![
        DataConcept {
            concept: "spot_price".into(),
            natural_language_triggers: vec![
                "spot price".into(), "RRP".into(), "electricity price".into(),
                "energy price".into(), "wholesale price".into(), "price".into(),
            ],
            primary_table: "DISPATCHPRICE".into(),
            primary_column: Some("RRP".into()),
            alternative_table: Some("TRADINGPRICE".into()),
            alternative_notes: Some("TRADINGPRICE has 30-minute trading interval prices. DISPATCHPRICE has 5-minute dispatch prices.".into()),
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "$/MWh".into(),
            notes: "RRP is in DISPATCHPRICE and TRADINGPRICE, NOT in DISPATCHREGIONSUM.".into(),
            formula: None,
        },
        DataConcept {
            concept: "demand".into(),
            natural_language_triggers: vec![
                "demand".into(), "total demand".into(), "electricity demand".into(),
                "load".into(), "consumption".into(),
            ],
            primary_table: "DISPATCHREGIONSUM".into(),
            primary_column: Some("TOTALDEMAND".into()),
            alternative_table: Some("DEMAND_HISTORIC".into()),
            alternative_notes: Some("DEMAND_HISTORIC is daily data only (all timestamps at 14:00). Use DISPATCHREGIONSUM for intraday analysis.".into()),
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "For intraday/hourly patterns, ALWAYS use DISPATCHREGIONSUM. DEMAND_HISTORIC is daily only.".into(),
            formula: None,
        },
        DataConcept {
            concept: "generation".into(),
            natural_language_triggers: vec![
                "generation".into(), "available generation".into(), "total generation".into(),
                "power generation".into(), "supply".into(),
            ],
            primary_table: "DISPATCHREGIONSUM".into(),
            primary_column: Some("AVAILABLEGENERATION".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "AVAILABLEGENERATION is total generation available in the region.".into(),
            formula: None,
        },
        DataConcept {
            concept: "generator_output".into(),
            natural_language_triggers: vec![
                "generator output".into(), "unit output".into(), "DUID output".into(),
                "top generators".into(), "highest output".into(), "most generation".into(),
                "largest generators".into(), "generator dispatch".into(),
            ],
            primary_table: "DISPATCHLOAD".into(),
            primary_column: Some("TOTALCLEARED".into()),
            alternative_table: Some("DISPATCH_UNIT_SCADA".into()),
            alternative_notes: Some("DISPATCH_UNIT_SCADA has SCADAVALUE (instantaneous MW from SCADA). DISPATCHLOAD has TOTALCLEARED (dispatch target MW).".into()),
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "GROUP BY DUID, filter by REGIONID and SETTLEMENTDATE range. DISPATCHLOAD has NO REGIONID — join from DUDETAILSUMMARY.".into(),
            formula: None,
        },
        DataConcept {
            concept: "fuel_type_generation".into(),
            natural_language_triggers: vec![
                "fuel type".into(), "generation by source".into(), "energy by source".into(),
                "renewable vs fossil".into(), "solar generation".into(), "wind generation".into(),
                "coal generation".into(), "gas generation".into(), "battery dispatch".into(),
            ],
            primary_table: "DISPATCHLOAD".into(),
            primary_column: Some("TOTALCLEARED".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec!["DUID_FUEL_TYPE_REFERENCE".into()],
            join_keys: vec!["DUID".into()],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "There is NO fuel type column in registration tables. Must JOIN a DUID fuel type reference table on DUID.".into(),
            formula: Some("SUM(TOTALCLEARED) * 5.0 / 60.0 AS energy_mwh".into()),
        },
        DataConcept {
            concept: "intermittent_scada".into(),
            natural_language_triggers: vec![
                "wind SCADA".into(), "solar SCADA".into(), "intermittent SCADA".into(),
                "wind farm output".into(), "solar farm output".into(),
            ],
            primary_table: "INTERMITTENT_GEN_SCADA".into(),
            primary_column: Some("SCADA_VALUE".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "Filter SCADA_TYPE = 'LOCL' for actual generation. Timestamp column is RUN_DATETIME (not SETTLEMENTDATE). ALWAYS include SCADA_TYPE filter in JOINs.".into(),
            formula: Some("SUM(SCADA_VALUE) * 5.0 / 60.0 AS energy_mwh".into()),
        },
        DataConcept {
            concept: "fcas_price".into(),
            natural_language_triggers: vec![
                "FCAS price".into(), "ancillary service price".into(),
                "regulation price".into(), "raise reg price".into(),
                "contingency price".into(), "RAISEREGRRP".into(), "LOWERREGRRP".into(),
            ],
            primary_table: "DISPATCHPRICE".into(),
            primary_column: None,
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "$/MW/hr".into(),
            notes: "ALL FCAS prices are in DISPATCHPRICE: RAISEREGRRP, LOWERREGRRP, RAISE6SECRRP, LOWER6SECRRP, RAISE60SECRRP, LOWER60SECRRP, RAISE5MINRRP, LOWER5MINRRP, RAISE1SECRRP, LOWER1SECRRP. NOT in DISPATCHREGIONSUM.".into(),
            formula: None,
        },
        DataConcept {
            concept: "fcas_volume".into(),
            natural_language_triggers: vec![
                "FCAS volume".into(), "FCAS dispatch".into(), "regulation procured".into(),
                "FCAS requirement".into(), "ancillary service volume".into(),
            ],
            primary_table: "DISPATCHREGIONSUM".into(),
            primary_column: None,
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "Use *LOCALDISPATCH columns for dispatched volumes. *REQ columns are NULL. For FCAS price AND volume, JOIN DISPATCHPRICE and DISPATCHREGIONSUM on SETTLEMENTDATE and REGIONID.".into(),
            formula: None,
        },
        DataConcept {
            concept: "revenue".into(),
            natural_language_triggers: vec![
                "revenue".into(), "earnings".into(), "income".into(), "profit".into(),
                "how much did X make".into(), "money made".into(), "generator revenue".into(),
            ],
            primary_table: "DISPATCHLOAD".into(),
            primary_column: Some("TOTALCLEARED".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec!["DISPATCHPRICE".into(), "DUDETAILSUMMARY".into()],
            join_keys: vec!["SETTLEMENTDATE".into(), "REGIONID".into(), "DUID".into()],
            resolution: "5min".into(),
            units: "$".into(),
            notes: "JOIN dispatch__unit_solution with dispatch__price on SETTLEMENTDATE. REGIONID comes from registration table (not in unit_solution). FCAS revenue uses *ACTUALAVAILABILITY, NOT dispatch targets.".into(),
            formula: Some(concat!(
                "SUM(\n",
                "  u.TOTALCLEARED * p.RRP +\n",
                "  u.RAISEREGACTUALAVAILABILITY * p.RAISEREGRRP +\n",
                "  u.LOWERREGACTUALAVAILABILITY * p.LOWERREGRRP +\n",
                "  u.RAISE6SECACTUALAVAILABILITY * p.RAISE6SECRRP +\n",
                "  u.LOWER6SECACTUALAVAILABILITY * p.LOWER6SECRRP +\n",
                "  u.RAISE60SECACTUALAVAILABILITY * p.RAISE60SECRRP +\n",
                "  u.LOWER60SECACTUALAVAILABILITY * p.LOWER60SECRRP +\n",
                "  u.RAISE5MINACTUALAVAILABILITY * p.RAISE5MINRRP +\n",
                "  u.LOWER5MINACTUALAVAILABILITY * p.LOWER5MINRRP +\n",
                "  u.RAISE1SECACTUALAVAILABILITY * p.RAISE1SECRRP +\n",
                "  u.LOWER1SECACTUALAVAILABILITY * p.LOWER1SECRRP\n",
                ") * 5.0 / 60.0 AS total_revenue_dollars",
            ).into()),
        },
        DataConcept {
            concept: "bids".into(),
            natural_language_triggers: vec![
                "bids".into(), "offers".into(), "bidding".into(), "bid price".into(),
                "bid volume".into(), "offer stack".into(),
            ],
            primary_table: "BIDDAYOFFER".into(),
            primary_column: None,
            alternative_table: Some("BIDOFFERPERIOD".into()),
            alternative_notes: Some("BIDDAYOFFER has daily bid summary. BIDOFFERPERIOD has per-interval bid details.".into()),
            join_tables: vec![],
            join_keys: vec![],
            resolution: "daily / 5min".into(),
            units: "$/MWh, MW".into(),
            notes: "Bid data includes price bands and quantity pairs.".into(),
            formula: None,
        },
        DataConcept {
            concept: "interconnector_flow".into(),
            natural_language_triggers: vec![
                "interconnector".into(), "interstate flow".into(), "transmission".into(),
                "QNI".into(), "Basslink".into(), "Heywood".into(), "Murraylink".into(),
            ],
            primary_table: "DISPATCHINTERCONNECTORRES".into(),
            primary_column: Some("MWFLOW".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "MW".into(),
            notes: "INTERCONNECTORID values: NSW1-QLD1 (QNI), VIC1-NSW1 (SNI/Terranora), V-SA (Heywood), V-S-MNSP1 (Murraylink), N-Q-MNSP1 (DirectLink), T-V-MNSP1 (Basslink). MWFLOW positive = flow towards second-named region.".into(),
            formula: None,
        },
        DataConcept {
            concept: "forecast_accuracy".into(),
            natural_language_triggers: vec![
                "forecast".into(), "pre-dispatch".into(), "forecast miss".into(),
                "forecast error".into(), "forecast accuracy".into(), "forecast vs actual".into(),
            ],
            primary_table: "PREDISPATCHREGIONSUM".into(),
            primary_column: Some("TOTALDEMAND".into()),
            alternative_table: Some("P5MIN_REGIONSOLUTION".into()),
            alternative_notes: Some("PREDISPATCHREGIONSUM has 30-min pre-dispatch forecasts. P5MIN_REGIONSOLUTION has 5-min pre-dispatch forecasts.".into()),
            join_tables: vec!["DISPATCHREGIONSUM".into()],
            join_keys: vec!["SETTLEMENTDATE/DATETIME".into(), "REGIONID".into()],
            resolution: "30min / 5min".into(),
            units: "MW".into(),
            notes: "Compare forecast TOTALDEMAND vs actual TOTALDEMAND. Pre-dispatch has multiple forecast runs per interval — use max(PREDISPATCHSEQNO) for latest. Forecast miss = actual - forecast.".into(),
            formula: Some("dispatch.TOTALDEMAND - predispatch.TOTALDEMAND AS forecast_miss_mw".into()),
        },
        DataConcept {
            concept: "registration".into(),
            natural_language_triggers: vec![
                "registration".into(), "generator details".into(), "registered generators".into(),
                "scheduled units".into(), "semi-scheduled".into(), "participant".into(),
                "DUID details".into(), "station".into(),
            ],
            primary_table: "DUDETAILSUMMARY".into(),
            primary_column: None,
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "reference".into(),
            units: "N/A".into(),
            notes: "Use SELECT DISTINCT to avoid duplicates. DISPATCHTYPE: GENERATOR, LOAD, BIDIRECTIONAL. SCHEDULE_TYPE: SCHEDULED, SEMI-SCHEDULED, NON-SCHEDULED. END_DATE uses 1900-01-01 sentinel (never NULL).".into(),
            formula: None,
        },
        DataConcept {
            concept: "settlements".into(),
            natural_language_triggers: vec![
                "settlements".into(), "billing".into(), "invoice".into(),
                "settlement amount".into(), "settlement payment".into(),
            ],
            primary_table: "SET_ENERGY_REGION_SUMMARY".into(),
            primary_column: None,
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "settlement run".into(),
            units: "$".into(),
            notes: "SET_ENERGY_REGION_SUMMARY is a REGIONAL aggregate (REGIONID, ENERGYCOST, GENERGY, NETENERGY). It has NO DUID column — never use for individual generator queries. For DUID-level revenue, use dispatch data with price JOINs.".into(),
            formula: None,
        },
        DataConcept {
            concept: "constraints".into(),
            natural_language_triggers: vec![
                "constraints".into(), "binding constraints".into(), "network constraints".into(),
                "constraint violations".into(), "congestion".into(),
            ],
            primary_table: "DISPATCHCONSTRAINT".into(),
            primary_column: Some("MARGINALVALUE".into()),
            alternative_table: None,
            alternative_notes: None,
            join_tables: vec![],
            join_keys: vec![],
            resolution: "5min".into(),
            units: "$/MW".into(),
            notes: "Binding constraints have MARGINALVALUE > 0. CONSTRAINTID is the GenConID.".into(),
            formula: None,
        },
    ]
}
