WITH

interconnector_dispatch AS (
    SELECT
        SETTLEMENTDATE,
        INTERCONNECTORID,
        avg(MWFLOW) AS MWFLOW,
        avg(METEREDMWFLOW) AS METEREDMWFLOW,
        avg(MWLOSSES) AS MWLOSSES,
        avg(EXPORTLIMIT) AS EXPORTLIMIT,
        avg(IMPORTLIMIT) AS IMPORTLIMIT,
        avg(MARGINALVALUE) AS MARGINALVALUE
    FROM semantic.dispatch_interconnectorres
    GROUP BY SETTLEMENTDATE, INTERCONNECTORID
)

SELECT
    INTERCONNECTORID,
    round(avg(abs(MWFLOW)), 2) AS avg_abs_flow_mw
FROM interconnector_dispatch
WHERE SETTLEMENTDATE >= now() - INTERVAL 7 DAY
GROUP BY INTERCONNECTORID
ORDER BY avg_abs_flow_mw DESC