SELECT
  PARTICIPANTID,
  SUM(REGISTEREDCAPACITY_MW) AS total_registered_capacity_mw
FROM semantic.unit_dimension
WHERE PARTICIPANTID IS NOT NULL
  AND REGISTEREDCAPACITY_MW IS NOT NULL
GROUP BY PARTICIPANTID
ORDER BY total_registered_capacity_mw DESC
LIMIT 20;